<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <IsPackable>false</IsPackable>
    <GenerateDocumentationFile>false</GenerateDocumentationFile>
    <!-- Suppress localization and other rules inappropriate for sample projects -->
    <NoWarn>$(NoWarn);CA1303</NoWarn>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Temporalio.Extensions.Hosting" Version="1.*" />
    <PackageReference Include="Temporalio.Extensions.OpenTelemetry" Version="1.*" />
    <PackageReference Include="Microsoft.Extensions.Hosting" Version="10.0.0" />
    <PackageReference Include="OpenTelemetry.Exporter.Console" Version="1.*" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\TemporalCommunity.DurableObjects\TemporalCommunity.DurableObjects.csproj" />
  </ItemGroup>
</Project>
