<Project>
  <!--#if (UseMinimalApi) -->
  <Sdk Name="Microsoft.NET.Sdk.Web" />
  <!--#else -->
  <Sdk Name="Microsoft.NET.Sdk" />
  <!--#endif -->

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Temporalio.Extensions.Hosting" Version="1.20.0" />
  </ItemGroup>

  <!--#if (IncludeOtel) -->
  <ItemGroup>
    <PackageReference Include="Temporalio.Extensions.OpenTelemetry" Version="1.20.0" />
    <PackageReference Include="OpenTelemetry.Extensions.Hosting" Version="1.18.0" />
  </ItemGroup>
  <!--#endif -->

  <!--#if (OtelWithoutAspire) -->
  <ItemGroup>
    <PackageReference Include="OpenTelemetry.Exporter.OpenTelemetryProtocol" Version="1.18.0" />
  </ItemGroup>
  <!--#endif -->

  <ItemGroup>
    <ProjectReference Include="..\XmlEncodedProjectName.Shared\XmlEncodedProjectName.Shared.csproj" />
<!--#if (IncludeAspire) -->
    <ProjectReference Include="..\XmlEncodedProjectName.ServiceDefaults\XmlEncodedProjectName.ServiceDefaults.csproj" />
<!--#endif -->
  </ItemGroup>

</Project>
