using System.Collections.Immutable;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace TemporalCommunity.DurableObjects.Analyzers;

/// <summary>Generates reflection-free concrete clients for DurableObject contracts.</summary>
[Generator(LanguageNames.CSharp)]
public sealed class DurableObjectClientGenerator : IIncrementalGenerator
{
    public const string UnsupportedContractId = "DO0005";

    private static readonly DiagnosticDescriptor s_unsupportedContract = new(
        UnsupportedContractId,
        "DurableObject contract cannot generate a client",
        "Contract '{0}' cannot generate a client: {1}",
        "Temporal.DurableObjects",
        DiagnosticSeverity.Error,
        isEnabledByDefault: true);

    private static readonly SymbolDisplayFormat s_typeFormat =
        SymbolDisplayFormat.FullyQualifiedFormat.WithMiscellaneousOptions(
            SymbolDisplayMiscellaneousOptions.IncludeNullableReferenceTypeModifier |
            SymbolDisplayMiscellaneousOptions.EscapeKeywordIdentifiers);

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var contracts = context.SyntaxProvider.CreateSyntaxProvider(
                static (node, _) => node is InterfaceDeclarationSyntax { BaseList: not null },
                static (syntaxContext, cancellationToken) =>
                {
                    var declaration = (InterfaceDeclarationSyntax)syntaxContext.Node;
                    return syntaxContext.SemanticModel.GetDeclaredSymbol(declaration, cancellationToken) as INamedTypeSymbol;
                })
            .Where(static symbol => symbol is not null && IsDurableObjectContract(symbol))
            .Collect();

        context.RegisterSourceOutput(contracts, static (sourceContext, symbols) =>
        {
            var seen = new HashSet<string>(StringComparer.Ordinal);
            var distinctContracts = symbols.OfType<INamedTypeSymbol>()
                .Where(contract => seen.Add(
                    contract.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat)))
                .ToArray();
            var collidingNames = new HashSet<string>(distinctContracts
                .GroupBy(contract => contract.ContainingNamespace.ToDisplayString() + "." + GetBaseName(contract))
                .Where(group => group.Count() > 1)
                .Select(group => group.Key), StringComparer.Ordinal);
            foreach (var contract in distinctContracts)
            {
                var generatedName = contract.ContainingNamespace.ToDisplayString() + "." + GetBaseName(contract);
                if (collidingNames.Contains(generatedName))
                {
                    sourceContext.ReportDiagnostic(Diagnostic.Create(
                        s_unsupportedContract,
                        contract.Locations.FirstOrDefault(location => location.IsInSource),
                        contract.Name,
                        "multiple contracts map to the same generated client name"));
                    continue;
                }

                GenerateClient(sourceContext, contract);
            }
        });

        context.RegisterPostInitializationOutput(static sourceContext =>
            sourceContext.AddSource(
                "ModuleInitializerAttribute.g.cs",
                SourceText.From(ModuleInitializerPolyfill, Encoding.UTF8)));
    }

    private static bool IsDurableObjectContract(INamedTypeSymbol symbol) =>
        symbol.AllInterfaces.Any(@interface =>
            @interface.ToDisplayString() == "TemporalCommunity.DurableObjects.IDurableObject");

    private static void GenerateClient(SourceProductionContext context, INamedTypeSymbol contract)
    {
        var error = GetUnsupportedReason(contract);
        if (error is not null)
        {
            context.ReportDiagnostic(Diagnostic.Create(
                s_unsupportedContract,
                contract.Locations.FirstOrDefault(location => location.IsInSource),
                contract.Name,
                error));
            return;
        }

        var namespaceName = contract.ContainingNamespace.IsGlobalNamespace
            ? null
            : contract.ContainingNamespace.ToDisplayString();
        var contractType = contract.ToDisplayString(s_typeFormat);
        var baseName = GetBaseName(contract);
        var clientName = baseName + "DurableObjectClient";
        var extensionName = baseName + "DurableObjectClientExtensions";
        var methods = GetContractMethods(contract);
        var source = new StringBuilder();
        source.AppendLine("// <auto-generated/>");
        source.AppendLine("#nullable enable");
        if (namespaceName is not null)
        {
            source.Append("namespace ").Append(namespaceName).AppendLine(";").AppendLine();
        }

        source.Append("public sealed class ").Append(clientName).Append(" : ")
            .Append(contractType).AppendLine().AppendLine("{");
        source.AppendLine("    private readonly global::TemporalCommunity.DurableObjects.DurableObjectClientInvoker _invoker;");
        source.AppendLine();
        source.Append("    internal ").Append(clientName)
            .AppendLine("(global::TemporalCommunity.DurableObjects.DurableObjectClientInvoker invoker)")
            .AppendLine("    {")
            .AppendLine("        _invoker = invoker;")
            .AppendLine("    }");

        foreach (var method in methods)
        {
            source.AppendLine();
            if (HasAttribute(method, "Temporalio.Workflows.WorkflowQueryAttribute"))
            {
                AppendQueryMethods(source, contractType, method);
            }
            else
            {
                AppendUpdateMethods(source, method);
            }
        }

        source.AppendLine("}").AppendLine();
        AppendExtensions(source, contractType, clientName, extensionName, baseName);
        source.AppendLine();
        source.Append("internal static class ").Append(clientName).AppendLine("Registration")
            .AppendLine("{")
            .AppendLine("    [global::System.Runtime.CompilerServices.ModuleInitializer]")
            .AppendLine("    internal static void Register()")
            .AppendLine("    {")
            .Append("        global::TemporalCommunity.DurableObjects.DurableObjectGeneratedClientRegistry.Register<")
            .Append(contractType).Append(">(invoker => new ").Append(clientName)
            .AppendLine("(invoker));")
            .AppendLine("    }")
            .AppendLine("}");

        context.AddSource(GetHintName(contract), SourceText.From(source.ToString(), Encoding.UTF8));
    }

    private static string? GetUnsupportedReason(INamedTypeSymbol contract)
    {
        if (contract.ContainingType is not null || contract.TypeParameters.Length != 0)
        {
            return "nested and generic contracts are not supported";
        }

        if (contract.DeclaredAccessibility != Accessibility.Public)
        {
            return "the contract must be public";
        }

        var baseName = GetBaseName(contract);
        if (contract.ContainingNamespace.GetTypeMembers(baseName + "DurableObjectClient").Length != 0 ||
            contract.ContainingNamespace.GetTypeMembers(baseName + "DurableObjectClientExtensions").Length != 0)
        {
            return "a generated client or extension type name is already declared";
        }

        if (contract.GetMembers().Concat<ISymbol>(contract.AllInterfaces.SelectMany(item => item.GetMembers()))
            .Any(member => member is IPropertySymbol or IEventSymbol))
        {
            return "properties and events are not supported on generated contracts";
        }

        var methods = GetContractMethods(contract);
        foreach (var method in methods)
        {
            if (method.MethodKind != MethodKind.Ordinary || method.IsStatic || method.IsGenericMethod ||
                method.Parameters.Any(parameter =>
                    parameter.RefKind != RefKind.None ||
                    parameter.Type.IsRefLikeType ||
                    parameter.Type.TypeKind is TypeKind.Pointer or TypeKind.FunctionPointer))
            {
                return $"method '{method.Name}' uses generics or ref-like parameters";
            }

            if (method.GetAttributes().Any(attribute =>
                    attribute.NamedArguments.Any(argument =>
                        argument.Key == "Dynamic" && argument.Value.Value is true)))
            {
                return $"dynamic handler '{method.Name}' is not supported";
            }

            if (method.Parameters.Any(parameter => parameter.Name == "callOptions"))
            {
                return $"method '{method.Name}' reserves the generated parameter name 'callOptions'";
            }

            if (HasAttribute(method, "Temporalio.Workflows.WorkflowUpdateAttribute") &&
                methods.Any(candidate =>
                    candidate.Name == method.Name &&
                    candidate.Parameters.Length == method.Parameters.Length + 1 &&
                    candidate.Parameters.Take(method.Parameters.Length).Select(parameter => parameter.Type)
                        .SequenceEqual(method.Parameters.Select(parameter => parameter.Type), SymbolEqualityComparer.Default) &&
                    candidate.Parameters[candidate.Parameters.Length - 1].Type.ToDisplayString() ==
                        "TemporalCommunity.DurableObjects.DurableObjectCallOptions"))
            {
                return $"update '{method.Name}' conflicts with its generated call-options overload";
            }

            if (HasAttribute(method, "Temporalio.Workflows.WorkflowQueryAttribute"))
            {
                var asyncName = method.Name + "Async";
                if (method.Name.EndsWith("Async", StringComparison.Ordinal) ||
                    methods.Any(candidate => candidate.Name == asyncName))
                {
                    return $"query '{method.Name}' cannot reserve generated method name '{asyncName}'";
                }
            }
        }

        return null;
    }

    private static ImmutableArray<IMethodSymbol> GetContractMethods(INamedTypeSymbol contract) =>
        contract.GetMembers().OfType<IMethodSymbol>()
            .Concat(contract.AllInterfaces
                .SelectMany(@interface => @interface.GetMembers().OfType<IMethodSymbol>()))
            .GroupBy(method => method.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat))
            .Select(group => group.First())
            .ToImmutableArray();

    private static string GetBaseName(INamedTypeSymbol contract) =>
        contract.Name.Length > 1 && contract.Name[0] == 'I' && char.IsUpper(contract.Name[1])
            ? contract.Name.Substring(1)
            : contract.Name;

    private static string GetHintName(INamedTypeSymbol contract) =>
        string.Concat(contract.ToDisplayString().Select(character =>
            char.IsLetterOrDigit(character) ? character : '_')) + ".DurableObjectClient.g.cs";

    private static void AppendUpdateMethods(StringBuilder source, IMethodSymbol method)
    {
        AppendMethodHeader(source, "    public ", method.ReturnType, method.Name, method.Parameters);
        source.Append(" => _invoker.ExecuteUpdateAsync");
        if (method.ReturnType is INamedTypeSymbol { IsGenericType: true } taskType)
        {
            source.Append('<').Append(taskType.TypeArguments[0].ToDisplayString(s_typeFormat)).Append('>');
        }

        source.Append('(').Append(Quote(GetWireName(method, isUpdate: true))).Append(", ")
            .Append(BuildArgs(method.Parameters)).AppendLine(");");

        source.AppendLine();
        AppendMethodHeader(
            source,
            "    public ",
            method.ReturnType,
            method.Name,
            method.Parameters,
            includeCallOptions: true);
        source.Append(" => _invoker.ExecuteUpdateAsync");
        if (method.ReturnType is INamedTypeSymbol { IsGenericType: true } genericTask)
        {
            source.Append('<').Append(genericTask.TypeArguments[0].ToDisplayString(s_typeFormat)).Append('>');
        }

        source.Append('(').Append(Quote(GetWireName(method, isUpdate: true))).Append(", ")
            .Append(BuildArgs(method.Parameters)).AppendLine(", callOptions);");
    }

    private static void AppendQueryMethods(
        StringBuilder source,
        string contractType,
        IMethodSymbol method)
    {
        AppendMethodHeader(
            source,
            "    ",
            method.ReturnType,
            contractType + "." + method.Name,
            method.Parameters);
        source.Append(" => ").Append(method.Name).Append("Async(")
            .Append(string.Join(", ", method.Parameters.Select(parameter => Escape(parameter.Name))))
            .AppendLine(").GetAwaiter().GetResult();");

        source.AppendLine();
        AppendTaskMethodHeader(source, method, includeCallOptions: false);
        source.Append(" => _invoker.QueryAsync<")
            .Append(method.ReturnType.ToDisplayString(s_typeFormat)).Append(">(")
            .Append(Quote(GetWireName(method, isUpdate: false))).Append(", ")
            .Append(BuildArgs(method.Parameters)).AppendLine(");");

        source.AppendLine();
        AppendTaskMethodHeader(source, method, includeCallOptions: true);
        source.Append(" => _invoker.QueryAsync<")
            .Append(method.ReturnType.ToDisplayString(s_typeFormat)).Append(">(")
            .Append(Quote(GetWireName(method, isUpdate: false))).Append(", ")
            .Append(BuildArgs(method.Parameters)).AppendLine(", callOptions);");
    }

    private static void AppendTaskMethodHeader(
        StringBuilder source,
        IMethodSymbol method,
        bool includeCallOptions)
    {
        source.Append("    public global::System.Threading.Tasks.Task<")
            .Append(method.ReturnType.ToDisplayString(s_typeFormat)).Append("> ")
            .Append(method.Name).Append("Async(");
        AppendParameters(source, method.Parameters, includeCallOptions);
        source.Append(')');
    }

    private static void AppendMethodHeader(
        StringBuilder source,
        string prefix,
        ITypeSymbol returnType,
        string methodName,
        ImmutableArray<IParameterSymbol> parameters,
        bool includeCallOptions = false)
    {
        source.Append(prefix).Append(returnType.ToDisplayString(s_typeFormat)).Append(' ')
            .Append(methodName).Append('(');
        AppendParameters(source, parameters, includeCallOptions);
        source.Append(')');
    }

    private static void AppendParameters(
        StringBuilder source,
        ImmutableArray<IParameterSymbol> parameters,
        bool includeCallOptions)
    {
        source.Append(string.Join(", ", parameters.Select(parameter =>
            parameter.Type.ToDisplayString(s_typeFormat) + " " + Escape(parameter.Name))));
        if (includeCallOptions)
        {
            if (parameters.Length != 0)
            {
                source.Append(", ");
            }

            source.Append("global::TemporalCommunity.DurableObjects.DurableObjectCallOptions callOptions");
        }
    }

    private static string BuildArgs(ImmutableArray<IParameterSymbol> parameters) =>
        parameters.Length == 0
            ? "global::System.Array.Empty<object?>()"
            : "new object?[] { " +
              string.Join(", ", parameters.Select(parameter => Escape(parameter.Name))) + " }";

    private static void AppendExtensions(
        StringBuilder source,
        string contractType,
        string clientName,
        string extensionName,
        string baseName)
    {
        source.Append("public static class ").Append(extensionName).AppendLine().AppendLine("{");
        AppendExtension(source, contractType, clientName, baseName, hasQueue: false, hasOptions: false);
        source.AppendLine();
        AppendExtension(source, contractType, clientName, baseName, hasQueue: false, hasOptions: true);
        source.AppendLine();
        AppendExtension(source, contractType, clientName, baseName, hasQueue: true, hasOptions: false);
        source.AppendLine();
        AppendExtension(source, contractType, clientName, baseName, hasQueue: true, hasOptions: true);
        source.AppendLine("}");
    }

    private static void AppendExtension(
        StringBuilder source,
        string contractType,
        string clientName,
        string baseName,
        bool hasQueue,
        bool hasOptions)
    {
        source.Append("    public static ").Append(clientName).Append(" Get").Append(baseName)
            .Append("Client(this global::TemporalCommunity.DurableObjects.IDurableObjectFactory factory, string objectId");
        if (hasQueue)
        {
            source.Append(", string taskQueue");
        }

        if (hasOptions)
        {
            source.Append(", global::TemporalCommunity.DurableObjects.DurableObjectCallOptions callOptions");
        }

        source.Append(") => (\n        ").Append(clientName).Append(")factory.Get<")
            .Append(contractType).Append(">(objectId");
        if (hasQueue)
        {
            source.Append(", taskQueue");
        }

        if (hasOptions)
        {
            source.Append(", callOptions");
        }

        source.AppendLine(");");
    }

    private static string GetWireName(IMethodSymbol method, bool isUpdate)
    {
        var attributeName = isUpdate
            ? "Temporalio.Workflows.WorkflowUpdateAttribute"
            : "Temporalio.Workflows.WorkflowQueryAttribute";
        var attribute = method.GetAttributes().First(item =>
            item.AttributeClass?.ToDisplayString() == attributeName);
        if (attribute.ConstructorArguments.Length != 0 &&
            attribute.ConstructorArguments[0].Value is string explicitName)
        {
            return explicitName;
        }

        return isUpdate && method.Name.EndsWith("Async", StringComparison.Ordinal)
            ? method.Name.Substring(0, method.Name.Length - "Async".Length)
            : method.Name;
    }

    private static string Escape(string identifier) =>
        SyntaxFacts.GetKeywordKind(identifier) == Microsoft.CodeAnalysis.CSharp.SyntaxKind.None
            ? identifier
            : "@" + identifier;

    private static string Quote(string value) => SymbolDisplay.FormatLiteral(value, quote: true);

    private static bool HasAttribute(ISymbol symbol, string metadataName) =>
        symbol.GetAttributes().Any(attribute => attribute.AttributeClass?.ToDisplayString() == metadataName);

    private const string ModuleInitializerPolyfill = """
        // <auto-generated/>
        #if !NET5_0_OR_GREATER
        namespace System.Runtime.CompilerServices
        {
            [global::System.AttributeUsage(global::System.AttributeTargets.Method, Inherited = false)]
            internal sealed class ModuleInitializerAttribute : global::System.Attribute
            {
            }
        }
        #endif
        """;
}
